name: open_extractor
description: Application to automatically extract information from Android devices.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  flutter_contacts: ^1.1.7
  permission_handler: ^11.0.1
  path_provider: ^2.0.11
  flutter_sms_inbox: ^1.0.4
  call_log: ^4.0.0
  flutter_lints: ^2.0.0
  csv: ^6.0.0

flutter:

  uses-material-design: true
